# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiaZUA1UKUDYAgb5vVxV_vSrpO92zCqJ
"""

1+1

a=10;

b=40

type(b)

type(y)

y=9.7

print("Hii Ayush")

t=86

p=898

print(p+t)

r=8.96

type(r)

s="srmcem"

s[0]

s[1]

s[2]

s[-6]

s[-1]

s[-2]

s[-3]

s[-4]

s[0:6:]

s[::-1]

s[::2]

s[0:3:-5]

s[0:3:2]

s=True

s=False

True*False

True/False

False/True

type(True)

a="Batch name is information technology"

a[0:33:7]

a[5:36:-1]

a[-1:-37:-2]

a[0:-37:-2]

l=[1,46,32,"ayush",89.96,(3+5j)]

l[0]

type(l)

s="Ramswaroop"

s.count('o')

s.count(' ')

s.lower()

s.upper()

len(s)

l[::-1]

l[5]

print(l)

l.append(98)

print(l)

l.pop()

l.pop(3)

l

l.insert(4,98)

"""l.insert(0,89.96)"""

l

e=(1,32,36,12,57,"True",True,False)

len(e[5])

len(e)

dict={"name":"age","Ayush":20,"Aman":21}

dict['name']

dict['Ayush']

len(dict)

l.remove(89.96)

print(l)

m={1,2,3,4,5}

type(m)

m.add(89.96)

m

m.update([89,96])

m

m.remove(89)

m

marks=81
if marks >= 90:
    print("grade : A+")
elif (marks >=80 and marks< 90):
    print("grade : A")
elif (marks >=70 and marks<80):
    print("grade : B+")
elif (marks >=60 and marks<70):
    print("grade : B")
elif (marks >=50 and marks<60):
    print("grade : C")
elif (marks >=40 and marks<50):
    print("grade : D")
else:
    print("fail")

menu={
    "Cold Coffee":40,
    "Tea":10,
    "Coffee":20,
    "Normal Pasta":50
}
print("Welcome to our cafe")
print(menu)
order_amount=0
item_1=input("enter the item name")
if item_1 in menu:
    order_amount += menu[item_1]
    print(f"your item {item_1} has been added to your order")
else:
    print(f"your intem {item_1} is not available")
another_order= input("Do you want to add another item? (yes/no)")
if another_order == "yes":
    item_2=input("enter the item name=")
    if item_2 in menu:
      order_amount += menu[item_2]
      print(f"your item {item_2} has been added to your order")
    else:
      print(f"your item {item_2} is not available")

print("your total bill{order_amount}")