# -*- coding: utf-8 -*-
"""Copy of Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16kfaxva65NaGGATiqawqj2EaejbtJdgL
"""

print("Student Result")
math=int(input("Enter marks of math:"))
english=int(input("Enter marks of english:"))
science=int(input("Enter marks of science:"))
computer=int(input("Enter marks of computer:"))

if(math>=90):
    print("math: A")
elif(math>=80):
    print("math: B")
elif(math>=70):
    print("math: C")
elif(math>=60):
    print("math: D")
if(english>=90):
    print("englisg: A")
elif(english>=80):
    print("englisg: B")
elif(english>=70):
    print("englisg: C")
elif(english>=60):
    print("englisg: D")
if(science>=90):
    print("science: A")
elif(science>=80):
    print("science: B")
elif(science>=70):
    print("science: C")
elif(science>=60):
    print("science: D")
if(computer>=90):
    print("computer: A")
elif(computer>=80):
    print("computer: B")
elif(computer>=70):
    print("computer: C")
elif(computer>=60):
    print("computer: D")


total=math+english+science+computer
percentage=total/4
print("Total marks:",total)
print("Percentage:",percentage)


if(percentage>=90):
    print("Grade A")
elif(percentage>=80):
    print("Grade B")
elif(percentage>=70):
    print("Grade C")
elif(percentage>=60):
    print("Grade D")