# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/163UdHctn2x9K7tqLM7jVGF0M2DO2OYtx
"""

def test():
  pass

def test1():
  print("This is my first function")

test1()

test1() + "sudh"

def test2():
  return "This is my first return "

test2()

test2() + "sudh"

def test3() :
  return "sudh" ,23, 345.56 , [1,2,4,4]

test3()

a,b,c,d, = test3()

def test4():
  a= 5+6/7
  return a

test4()

def test5(a,b,c):
  d = a+b/c
  return d

test5(11,44,66)

def test6(a,b):
  return a+b

test6(34.56,6)

test6("sudh" , "kumar")

test6((1,2,3,4,4),(4,5,7,5))

l = [1,2,3,4,"sudh","kumar",[1,2,3,4,5,6,]]

l1 = []
for i in l :
  if type(i) == int or type(i) == float :
    l1.append(i)

l1

def test7(l):
  l1 = []
  for i in l :
    if type(i) == int or type(i) == float :
      l1.append(i)
  return l1

print(l)

def test8(a):
  l=[]
  for i in a:
    if type(i) == list:
      for j in i:
        l.append(j)
    else:
      if type(i) == int or type(i) == float:
        l.append(i)
  return l

test8(l)

def calculator():
  def add(a,b):
    return a+b
  def sub(a,b):
    return a-b
  def mul(a,b):
    return a*b
  def div(a,b):
    return a/b
  a=int(input("Enter a number:"))
  b=int(input("Enter a number:"))
  print("1.Add 2.Sub 3.Mul 4.Div")
  ch=int(input("Enter your choice:"))
  if ch==1:
    print(add(a,b))
  elif ch==2:
    print(sub(a,b))
  elif ch==3:
    print(mul(a,b))
  elif ch==4:
    print(div(a,b))
  else:
    print("Invalid choice")
calculator()

pin=6998
def atm():
  p=int(input("Enter your pin:"))
  if(p==pin):
    ch=int(input("1.Balance 2.Withdraw 3.Deposit 4.Exit"))
    if ch==1:
      print("Your balance is 10000")
    elif ch==2:
      w=int(input("Enter the amount to withdraw:"))
      print("Your balance is",10000-w)
    elif ch==3:
      d=int(input("Enter the amount to deposit:"))
      print("Your balance is",10000+d)
    elif ch==4:
      print("Thank you for using our service")
    else:
      print("Invalid choice")
  else:
    print("Invalid pin")
atm()

def test_fib(n):
  a,b = 0,1
  for i in range(n):
    yield a
    a,b = b , a+b

for i in test_fib(10):
  print(i)

test_fib(10)

a="Ayush"

for i in a:
  print(i)